import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles({
    wrapper: {
        display: "flex",
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        margin: 20,
    },
    picker: {
        display: "flex",
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 14,
        fontWeightLight: 200,
        fontWeightRegular: 200,
        htmlFontSize: 16,
        padding: 0,
        margin:0,
        fontFamily: "Roboto",
        color: '#F1EEE9',
    },
    content: {
        display: "flex",
        width: '80wv',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: '40px',
    },
    item: {
        display: "flex",
        width: '100%',
        flexDirection: 'column',
    },
    text: {
        fontSize: 18,
        fontWeight: 200,
        htmlFontSize: 16,
        color: '#F1EEE9',
        padding: 0,
        margin:0,
        fontFamily: "Roboto",
    },
    circle: {
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '500px',
        margin: '10px',
        width: '130px',
        height: '130px',
        fontSize: 36,
        fontWeight: 200,
        htmlFontSize: 16,
        color: '#702433',
        fontFamily: "Roboto",
    },
    group: {
        display: "flex",
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    button: {
        color: 'white',
        width: '200px',
        height: '60px',
        display: 'flex',
        alignItems: 'center',
        alignSelf: 'center',
    }
});
