import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles({
    wrapper: {
        display:'flex',
        flexDirection:'row',
        backgroundColor: '#eeeeee'
    },
    adminBar: {
        display:'flex',
        flexDirection:'row',
        width: '100%'
    },
    friendsContainer: {
        display: 'flex',
        overflow: 'scroll',
        overflowX: 'hidden',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        width: '15vw',
        minWidth: 180,
        padding: '2% 1%',
        backgroundColor:'#a2505c',
        opacity: 0.85,
        '&:hover': {
            backgroundColor: '#a2505c',
            opacity: 1,
        },
    },
    friendRow : {
        minWidth: '6vw',
        maxWidth: '15vw',
        display:'flex',
        flexDirection:'row',
        justifyContent: 'space-between',
        gap: 10,
        alignItems: 'center',
        alignSelf: 'flex-start',
        marginBottom: 10,
        color: '#000000',
        fontSize: 12,
    },
    mainContainer: {
        display: 'flex',
        flex: 1,
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        height: '100vh',
        padding: '1% 2%',
    },
    topPanel: {
        display:'flex',
        width: '100%',
        height: 100,
        background: '#858585',
        borderRadius: 5,
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
    },
    userBlock: {
        display: "flex",
        flexDirection: "row",
        height: '15vh',
        width: '80vw',
        marginTop: 10,
        alignContent: 'space-between'
    },
    avatar: {
       position: "relative",
        top: -30,
        left: 20,
        width: 120,
        height: 120,
        border: "7px solid white",
        boxShadow: '2px 2px 10px gray',
    },
    userInfo: {
        display: 'flex',
        flexDirection: 'column',
        marginLeft: 40,
       
    },
    username: {
        fontSize: 20,
        fontWeightLight: 200,
        fontWeightRegular: 600,
        htmlFontSize: 16,
        color: 'black',
        padding: 0,
        margin:0,
        fontFamily: "Roboto",
    },
    otherInfo: {
        fontSize: 14,
        fontWeightLight: 200,
        fontWeightRegular: 200,
        htmlFontSize: 16,
        color: 'darkgray',
        padding: 0,
        margin:0,
        fontFamily: "Roboto",
    },
    watchHistoryVisibility: {
        fontSize: 14,
        padding: 0,
        margin:0,
        fontFamily: "Roboto",
        htmlFontSize: 16,
        fontWeightRegular: 200,
        fontWeightLight: 200,
    },
    watchHistoryConfiguration: {
        display: "flex",
    },
    editButton: {
        alignSelf: 'flex-start',
        backgroundColor: '#6180a6',
        color: '#eeeeee',
        '&:hover': {
            backgroundColor: '#335477',
            opacity: 0.8,
        },
        marginLeft: 10,
    },
    blocksWrapper: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 30,
    },
    movieText: {
        fontSize: 14,
        fontWeightLight: 200,
        fontWeightRegular: 200,
        htmlFontSize: 16,
        color: 'black',
        padding: 0,
        margin:0,
        fontFamily: "Roboto",
    },
    text: {
    fontSize: 14,
    fontWeightLight: 200,
    fontWeightRegular: 300,
    htmlFontSize: 16,
    color: 'white',
    padding: 0,
    margin:0,
},
    blockInformation: {
        display: 'flex',
        flex: 1,
        flexDirection: 'column',
        flexWrap: 'no-wrap',
        minWidth: 500,
        minHeight: '2vh',
        maxHeight: 200,
        backgroundColor: "white",
        margin: 10,
        paddingTop: 12,
        paddingLeft: 25,
        paddingBottom: 12,
        paddingRight: 25,
        borderRadius: 5,
        boxShadow: '0px 0px 10px lightgray',
    },
    table: {
        textAlign: 'left',
        tableLayout: 'fixed',
        borderCollapse: 'collapse',
    },
    tableTitle: {
        fontSize: 14,
        fontWeightLight: 200,
        fontWeightRegular: 300,
        htmlFontSize: 16,
        color: 'black',
        padding: 0,
        margin:0,
    },
    blockTitle: {
        fontSize: 18,
        fontWeightLight: 200,
        fontWeightRegular: 200,
        htmlFontSize: 20,
        color: 'black',
        padding: 0,
        margin:0,
        fontFamily: "Roboto",
    },
    button: {
        width: '50%',
        height: '2%',
        flexShrink: 1,
        flexGrow: 1,
        flexBasis: '6vh',
        background: '#eeeeee',
        borderRadius: 5,
        padding: 0,
    },
    chart: {
        display: "flex",
        width:400,
        height: 160,
        padding: 0,
    },
    privateCard :{
        marginTop: 100,
        marginLeft: 430,
        padding: 20
    }
});
